name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Extract version from tag
        uses: damienaicheh/extract-version-from-tag-action@v1.0.0

      - name: Update gradle version for Android
        uses: damienaicheh/update-android-version-gradle-action@v1.0.0
        with:
          build-gradle-path: './app/build.gradle'
          version-code:  ${{ env.MAJOR }} * 1000 + ${{ env.MINOR }} * 100 + ${{ env.PATCH }} * 10 + ${{ env.NUMBER_OF_COMMITS }}
          version-name: '${{ env.MAJOR }}.${{ env.MINOR }}.${{ env.PATCH }}'
          print-file: true

      - name: Increase Java heap space
        run: echo "org.gradle.jvmargs=-Xmx4096M" >> gradle.properties

      - name: Clean project
        run: ./gradlew clean

      - name: Assemble
        run: ./gradlew assembleDebug
